### PR TITLE
Add composer test script

### PR DESCRIPTION
**Pull request by dominicimhof**

### CODE REVIEW

**Comment by pyrech** [comment]
Hi,
Thank you for this PR but I'm not sure to understand what are the advantages of a test script?

**Comment by MaxGfeller** [comment]
+1 for this.

Composer supports defining custom scripts. Major PHP projects started adapting this and are now all defining their own test scripts. Here are some examples:

https://github.com/composer/composer/blob/master/composer.json#L63-L65
https://github.com/Seldaek/monolog/blob/master/composer.json#L60-L63

The advantage of this is pretty obvious; you don't have to have a global phpunit/whatever setup and can just run composer test for each library that you want to start working with.

I have written an [article](http://maxgfeller.com/blog/2014/07/22/composer-test/) about this a while ago, if it interests you.

**Comment by paulmallet** [comment]
:+1:

**Comment by pyrech** [comment]
Thank you for your explanations @MaxGfeller. If this is becoming the standard, let's merge it. :)
Thank you @dominicimhof for your PR.

**Comment by MaxGfeller** [comment]
Awesome, thank you @pyrech and @dominicimhof! :)

**Pull request merged**
